#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 kaayzouee
# Author: https://github.com/kaayzouee

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".webp",
}

MANIFEST_PATH = Path("manifest.tsv")
REPOSITORY_OWNER = "kaayzouee"
REPOSITORY_NAME = "neodots-wallpaper"

LFS_VERSION_PREFIX = b"version https://git-lfs.github.com/spec/v1"


def git_revision() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )

    revision = result.stdout.strip()

    if len(revision) != 40 or any(
        character not in "0123456789abcdef"
        for character in revision.lower()
    ):
        raise RuntimeError(f"invalid git revision returned by git: {revision}")

    return revision


def parse_lfs_pointer(data: bytes) -> tuple[str, int] | None:
    if not data.startswith(LFS_VERSION_PREFIX):
        return None

    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return None

    oid: str | None = None
    size: int | None = None

    for line in text.splitlines():
        if line.startswith("oid sha256:"):
            oid = line.removeprefix("oid sha256:").strip()
        elif line.startswith("size "):
            raw_size = line.removeprefix("size ").strip()
            size = int(raw_size)

    if oid is None or size is None:
        raise RuntimeError("malformed Git LFS pointer")

    if len(oid) != 64 or any(
        character not in "0123456789abcdef"
        for character in oid.lower()
    ):
        raise RuntimeError(f"invalid Git LFS SHA-256 object ID: {oid}")

    if size <= 0:
        raise RuntimeError(f"invalid Git LFS object size: {size}")

    return oid.lower(), size


def file_metadata(path: Path) -> tuple[str, int]:
    data = path.read_bytes()

    lfs_metadata = parse_lfs_pointer(data)

    if lfs_metadata is not None:
        return lfs_metadata

    digest = hashlib.sha256(data).hexdigest()
    return digest, len(data)


def wallpaper_id(path: Path) -> str:
    name = path.name

    if any(character in name for character in "\t\r\n"):
        raise RuntimeError(f"wallpaper filename contains control whitespace: {name}")

    return name


def wallpaper_format(path: Path) -> str:
    extension = path.suffix.lower().removeprefix(".")

    if extension not in {extension.removeprefix(".") for extension in IMAGE_EXTENSIONS}:
        raise RuntimeError(f"unsupported wallpaper extension: {path}")

    return extension


def main() -> None:
    root = Path.cwd()
    revision = git_revision()

    entries: list[tuple[str, str, str, int, str]] = []

    for path in sorted(root.iterdir(), key=lambda value: value.name):
        if not path.is_file():
            continue

        extension = path.suffix.lower()

        if extension not in IMAGE_EXTENSIONS:
            continue

        digest, size = file_metadata(path)
        identifier = wallpaper_id(path)
        image_format = wallpaper_format(path)

        entries.append(
            (
                identifier,
                path.name,
                digest,
                size,
                image_format,
            )
        )

    seen_ids: set[str] = set()
    seen_filenames: set[str] = set()

    for identifier, filename, _, _, _ in entries:
        if identifier in seen_ids:
            raise RuntimeError(f"duplicate wallpaper ID: {identifier}")

        if filename in seen_filenames:
            raise RuntimeError(f"duplicate wallpaper filename: {filename}")

        seen_ids.add(identifier)
        seen_filenames.add(filename)

    lines = [
        "# Generated by tools/generate-manifest.py. Do not edit manually.",
        "# Git LFS SHA-256 object IDs are used directly for LFS-backed images.",
        f"schema\t1",
        f"repository\t{REPOSITORY_OWNER}/{REPOSITORY_NAME}",
        f"source_revision\t{revision}",
        "wallpaper\tid\tfilename\tsha256\tsize\tformat",
    ]

    for identifier, filename, digest, size, image_format in entries:
        lines.append(
            f"wallpaper\t{identifier}\t{filename}\t{digest}\t{size}\t{image_format}"
        )

    MANIFEST_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"generated {MANIFEST_PATH} with {len(entries)} wallpapers "
        f"for source revision {revision}"
    )


if __name__ == "__main__":
    main()
